AWSTemplateFormatVersion: 2010-09-09
Description: Companies API CloudFromation template
Parameters:
  ResourcePrefix:
    Type: String
    Description: Resource prefix to use when creating necessary objects
    AllowedPattern: '^[a-z0-9][a-z0-9-]+$'
    ConstraintDescription: 'Resource prefix can only contain lower-case letters, numbers, and dashes'
    MaxLength: 30
Resources:
  ApiGatewayRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Description: The API resource
      Name: !Ref ResourcePrefix
  ApiGatewayResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt 
        - ApiGatewayRestApi
        - RootResourceId
      PathPart: companies
  ApiGatewayPostMethod:
    Type: 'AWS::ApiGateway::Method'
    DependsOn: LambdaPermission
    Properties:
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref ApiGatewayAuthorizer
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResource
      HttpMethod: POST
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Join 
          - ''
          - - 'arn:aws:apigateway:'
            - !Ref 'AWS::Region'
            - ':lambda:path/2015-03-31/functions/'
            - !GetAtt 
              - Lambda
              - Arn
            - /invocations
      RequestParameters:
        method.request.header.Authorization: true
  ApiGatewatDeployment:
    DependsOn:
      - ApiGatewayPostMethod
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      Description: Development Stage
      StageName: Development
  Lambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: gofit-lambda-functions
        S3Key: companies-lambda.zip
      Handler: main
      MemorySize: 128
      Role: !GetAtt 
        - LambdaRole
        - Arn
      Runtime: go1.x
      Timeout: 60
  LambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      FunctionName: !GetAtt 
        - Lambda
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join 
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':'
          - !Ref ApiGatewayRestApi
          - /*
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
  ApiGatewayAuthorizer:
    Type: 'AWS::ApiGateway::Authorizer'
    Properties:
      AuthorizerCredentials: !GetAtt 
        - ApiGatewayAuthorizerRole
        - Arn
      AuthorizerResultTtlInSeconds: 300
      AuthorizerUri: !Join 
        - ''
        - - 'arn:aws:apigateway:'
          - !Ref 'AWS::Region'
          - ':lambda:path/2015-03-31/functions/'
          - !ImportValue gofit-custom-authorizer-lambda
          - /invocations
      IdentitySource: method.request.header.Authorization
      Name: api-authorizer
      RestApiId: !Ref ApiGatewayRestApi
      Type: TOKEN
  ApiGatewayAuthorizerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: lambda
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'lambda:invokeFunction'
                Resource: !ImportValue gofit-custom-authorizer-lambda
  
Outputs:
  AwsAccountId:
    Value: !Ref 'AWS::AccountId'
    Description: Account ID of the AWS account
  AwsRegion:
    Value: !Ref 'AWS::Region'
    Description: Region of the AWS deployment
  ApiGatewayRestApi:
    Value: !Ref ApiGatewayRestApi
    Description: Name of the ApiGatewayRestApi
